language: node_js
sudo: false
cache:
  directories:
    - node
dist: trusty
node_js:
  - '8.9.4'
branches:
  only:
  - master
before_install:
 - npm install @angular/cli
 - npm run lib
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - npm run build
 - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
